### ISSUE TITLE
Mixing of Norwegian and English

### ISSUE THREAD

**Issue by FredrikAugust** [blauks/spotify-api-testing#5]
https://github.com/blauks/spotify-api-testing/blob/d2ca889bd35b7042dcb81ba24174584d9c793d67/frontend/src/App.js#L15

Mixing of Norwegian and English?

**Comment by FredrikAugust** [comment]
Any updates on this?

**Comment by blauks** [comment]
I won't fix this

**Comment by FredrikAugust** [comment]
_oh_
